spring:
  application:
    name: example-social-network
  liquibase:
    change-log: classpath:/liquibase/db.changelog-master.yaml
  datasource:
    url: jdbc:postgresql://localhost:5432/your_database_name
    username: your_username
    password: your_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none